build: off
version: "0.1.13-{build}"

image:
  - macOS
  - Visual Studio 2019

platform:
  - x64

environment:
  matrix:
    - TOXENV: py39
      PYTHON_WIN: "C:\\Python39"
      PYTHON_MAC: "venv3.9.1"
      PYTHON_UBU: "venv3.9/bin/python"
      PYTHON_VERSION: "3.9.1"
      PYTHON_ARCH: "64"


for:
  - 
    matrix:
      only:
        - image: Visual Studio 2019
    init:
      - "ECHO %PYTHON_WIN% %PYTHON_VERSION% %PYTHON_ARCH%"
      - "%PYTHON_WIN%\\python.exe --version"

    install:
      - "git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git"
      - "powershell gl-ci-helpers/appveyor/install_opengl.ps1"
      - "SET PYVISTA_OFF_SCREEN=True"
      - "%PYTHON_WIN%\\python.exe -m pip install -r requirements.txt"
      - "%PYTHON_WIN%\\python.exe -m pip install cx_freeze pymorphy2_dicts"
      - "%PYTHON_WIN%\\python.exe -m pip install ."
      - "cd cx_freeze"
      - "%PYTHON_WIN%\\python.exe setup.py bdist_msi"
      - ps: "ls"

    artifacts:
      path: cx_freeze/dist/*.msi
      name: Windows App
        
  -
    matrix:
      only:
        - image: macOS
    
    init:
      - "ls"
      - "echo $PYTHON_MAC $PYTHON_VERSION $PYTHON_ARCH"
      - "$HOME/$PYTHON_MAC/bin/python --version"
    
    install:
      - "$HOME/$PYTHON_MAC/bin/python -m pip install -r requirements.txt"
      - "$HOME/$PYTHON_MAC/bin/python -m pip install cx_freeze pymorphy2_dicts"
      - "$HOME/$PYTHON_MAC/bin/python -m pip install ."
      - "cd cx_freeze"
      - "$HOME/$PYTHON_MAC/bin/python setup.py bdist_mac --iconfile icon.icns --bundle-name=ssmtool --custom-info-plist Info.plist -q"
      - "npm i -g create-dmg"
      - "cd build"
      - "create-dmg ssmtool.app || true"
      - "mv \"ssmtool undefined.dmg\" ssmtool-$APPVEYOR_REPO_TAG_NAME.dmg"
      - "ls"
      - "cd ../../"

    artifacts:
      path: cx_freeze/build/ssmtool-$(APPVEYOR_REPO_TAG_NAME).dmg
      name: Mac App


deploy:
  description: new release
  provider: GitHub
  auth_token:
    secure: GMdaty/QRo0ATH06dsAQ2LtyUTQUuk45Pp23OTDKBevsBdnhCPW6iAGPcYO1Vyj3
  artifact: Windows App, Mac App
  draft: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true