build: off
version: "0.1.13-{build}"

environment:
  matrix:
    - TOXENV: py39
      PYTHON: "C:\\Python39"
      PYTHON_VERSION: "3.9.1"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "%PYTHON%\\python.exe --version"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install cx_freeze"
  - "%PYTHON%\\python.exe cx_freeze/setup.py bdist_msi"
  - ps: "ls"
