build: off
version: "0.1.13-{build}"

image:
  - macOS
  - Visual Studio 2019

platform:
  - x64

environment:
  matrix:
    - TOXENV: py39
      PYTHON_WIN: "C:\\Python39"
      PYTHON_MAC: "venv3.9.1"
      PYTHON_VERSION: "3.9.1"
      PYTHON_ARCH: "64"


for:
  - 
    matrix:
      only:
        - image: Visual Studio 2019
    init:
      - "ECHO %PYTHON_WIN% %PYTHON_VERSION% %PYTHON_ARCH%"
      - "%PYTHON_WIN%\\python.exe --version"

    install:
      - "%PYTHON_WIN%\\python.exe -m pip install -r requirements.txt"
      - "%PYTHON_WIN%\\python.exe -m pip install cx_freeze pymorphy2_dicts"
      - "%PYTHON_WIN%\\python.exe -m pip install ."
      - "cd cx_freeze"
      - "%PYTHON_WIN%\\python.exe setup.py bdist_msi"
      - ps: "ls"

  -
    matrix:
      only:
        - image: macOS
    
    init:
      - "ls"
      - "echo $PYTHON_MAC $PYTHON_VERSION $PYTHON_ARCH"
      - "$HOME/$PYTHON_MAC/bin/python --version"
    
    install:
      - "$HOME/$PYTHON_MAC/bin/python -m pip install -r requirements.txt"
      - "$HOME/$PYTHON_MAC/bin/python -m pip install cx_freeze pymorphy2_dicts"
      - "cd cx_freeze"
      - "$HOME/$PYTHON_MAC/bin/python setup.py bdist_dmg"