build: off
version: "0.1.13-{build}"

image:
  - Visual Studio 2019

environment:
  matrix:
    - TOXENV: py39
      PYTHON: "C:\\Python39"
      PYTHON_VERSION: "3.9.1"
      PYTHON_ARCH: "64"
      PYTHON_CMD: "C:\\Python39\\python.exe"
      BUILD_CMD: "bdist_msi"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "%PYTHON%\\python.exe --version"

install:
  - ps: {PYTHON_CMD} -m pip install -r requirements.txt
  - ps: {PYTHON_CMD} -m pip install cx_freeze pymorphy2_dicts
  - ps: {PYTHON_CMD} -m pip install .
  - ps: cd cx_freeze
  - ps: {PYTHON_CMD} setup.py {BUILD_CMD}
  - ps: "ls"
